import argparse
import csv
import itertools
import statistics
from pathlib import Path


FRIENDLY_MODEL_NAMES = {
    "raehmc_no_cl": "RAE-HMC (w/o CL)",
    "raehmc_ss_cl": "RAE-HMC (w/ L_SS)",
    "raehmc_hnm_cl": "RAE-HMC (w/ L_HNM)",
    "raehmc_cl": "RAE-HMC (w/ L_SS+L_HNM)",
    "raehmc": "RAE-HMC",
    "bert_ft": "BERT-FT",
    "hgclr": "HGCLR",
    "hill": "HILL",
    "hpt": "HPT",
    "global_only": "HMCN-Global only",
    "local_only": "HMCN-Local only",
    "memory_only": "Retrieval only",
    "hmcn_logit": "HMCN (w/ Logit residual)",
    "hmcn_prob": "HMCN (w/ Prob residual)",
    "full_logit": "HMCN + Retrieval (w/ Logit residual)",
    "full_prob": "HMCN + Retrieval (w/ Prob residual)",
    "global_local": "HMCN (w/ Prob residual)",
    "all": "HMCN + Retrieval (w/ Prob residual)",
    "global": "HMCN-Global only",
    "local": "HMCN-Local only",
    "sum": "HMCN (direct-sum fusion)",
    "residual": "HMCN (w/ residual fusion)",
    "raehmc_Sum": "RAE-HMC (direct-sum backbone + post-hoc retrieval)",
    "raehmc_Residual": "RAE-HMC (residual backbone + post-hoc retrieval)",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze paired-test CSV and export mean/std and paired t-test results."
    )
    parser.add_argument(
        "--input-csv",
        required=True,
        help="CSV generated by run_baselines_multiseed.py or ablation scripts.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Default: same directory as input CSV.",
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help="Default: input CSV stem.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Significance threshold used in the result tables.",
    )
    return parser.parse_args()


def load_rows(csv_path: Path) -> tuple[list[str], list[dict[str, str]]]:
    def normalize_fieldname(name: str) -> str:
        if name.endswith("_mic"):
            return f"{name[:-len('_mic')]}_micro"
        if name.endswith("_mac"):
            return f"{name[:-len('_mac')]}_macro"
        return name

    with csv_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = []
        for name in list(reader.fieldnames or []):
            normalized = normalize_fieldname(name)
            if normalized not in fieldnames:
                fieldnames.append(normalized)
        rows = []
        for row in reader:
            if not row:
                continue
            if row.get("seed", "") in ("", None):
                continue
            normalized_row = {}
            for key, value in row.items():
                normalized_row[normalize_fieldname(key)] = value if value is not None else ""
            rows.append(normalized_row)
    if not rows:
        raise ValueError(f"No data rows found in {csv_path}")
    return fieldnames, rows


def infer_models(fieldnames: list[str]) -> list[str]:
    models: list[str] = []
    for name in fieldnames:
        if name == "seed":
            continue
        if name.endswith("_micro"):
            model = name[: -len("_micro")]
        elif name.endswith("_macro"):
            model = name[: -len("_macro")]
        else:
            continue
        if f"{model}_micro" in fieldnames and f"{model}_macro" in fieldnames and model not in models:
            models.append(model)
    return models


def safe_float(value: str) -> float | None:
    if value in ("", None):
        return None
    return float(value)


def sample_std(values: list[float]) -> float:
    if len(values) <= 1:
        return 0.0
    return statistics.stdev(values)


def mean_pm_std_text(mean_value: float, std_value: float) -> str:
    return f"{mean_value:.4f} ± {std_value:.4f}"


def mean_pm_std_pct_text(mean_value: float, std_value: float) -> str:
    return f"{mean_value * 100:.2f} ± {std_value * 100:.2f}"


def metric_values(rows: list[dict[str, str]], model: str, metric: str) -> list[float]:
    key = f"{model}_{metric}"
    values = []
    for row in rows:
        value = safe_float(row.get(key, ""))
        if value is not None:
            values.append(value)
    return values


def paired_values(rows: list[dict[str, str]], model_a: str, model_b: str, metric: str) -> tuple[list[int], list[float], list[float]]:
    seeds: list[int] = []
    values_a: list[float] = []
    values_b: list[float] = []
    key_a = f"{model_a}_{metric}"
    key_b = f"{model_b}_{metric}"
    for row in rows:
        value_a = safe_float(row.get(key_a, ""))
        value_b = safe_float(row.get(key_b, ""))
        if value_a is None or value_b is None:
            continue
        seeds.append(int(row["seed"]))
        values_a.append(value_a)
        values_b.append(value_b)
    return seeds, values_a, values_b


def write_csv(csv_path: Path, fieldnames: list[str], rows: list[dict]):
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def analyze_mean_std(rows: list[dict[str, str]], models: list[str]) -> list[dict[str, object]]:
    table_rows: list[dict[str, object]] = []
    for model in models:
        for metric in ("micro", "macro"):
            values = metric_values(rows, model, metric)
            if not values:
                continue
            mean_value = statistics.mean(values)
            std_value = sample_std(values)
            table_rows.append(
                {
                    "model_key": model,
                    "model": FRIENDLY_MODEL_NAMES.get(model, model),
                    "metric": metric,
                    "n": len(values),
                    "mean": f"{mean_value:.4f}",
                    "std": f"{std_value:.4f}",
                    "mean_pm_std": mean_pm_std_text(mean_value, std_value),
                    "mean_pm_std_pct": mean_pm_std_pct_text(mean_value, std_value),
                }
            )
    return table_rows


def analyze_paired_tests(rows: list[dict[str, str]], models: list[str], alpha: float):
    try:
        from scipy.stats import ttest_rel
    except ImportError as exc:
        raise RuntimeError(
            "SciPy is required for analyze_paired_test.py. "
            "Run this script in `hgclr-gpu` or `hill-gpu`, or install scipy in your current environment."
        ) from exc

    paired_t_rows: list[dict[str, object]] = []

    for model_a, model_b in itertools.combinations(models, 2):
        for metric in ("micro", "macro"):
            seeds, values_a, values_b = paired_values(rows, model_a, model_b, metric)
            if not values_a:
                continue
            diffs = [a - b for a, b in zip(values_a, values_b)]
            mean_a = statistics.mean(values_a)
            std_a = sample_std(values_a)
            mean_b = statistics.mean(values_b)
            std_b = sample_std(values_b)
            mean_diff = statistics.mean(diffs)
            std_diff = sample_std(diffs)

            t_result = ttest_rel(values_a, values_b, alternative="two-sided")
            paired_t_rows.append(
                {
                    "model_a_key": model_a,
                    "model_a": FRIENDLY_MODEL_NAMES.get(model_a, model_a),
                    "model_b_key": model_b,
                    "model_b": FRIENDLY_MODEL_NAMES.get(model_b, model_b),
                    "metric": metric,
                    "n": len(values_a),
                    "paired_seeds": " ".join(str(seed) for seed in seeds),
                    "mean_a": f"{mean_a:.4f}",
                    "std_a": f"{std_a:.4f}",
                    "mean_b": f"{mean_b:.4f}",
                    "std_b": f"{std_b:.4f}",
                    "mean_diff_a_minus_b": f"{mean_diff:.4f}",
                    "std_diff": f"{std_diff:.4f}",
                    "t_statistic": f"{float(t_result.statistic):.6f}",
                    "p_value": f"{float(t_result.pvalue):.10g}",
                    "significant": str(float(t_result.pvalue) < alpha),
                }
            )

    return paired_t_rows


def print_terminal_summary(mean_std_rows: list[dict[str, object]], paired_t_rows: list[dict[str, object]]):
    print("\nMean ± std")
    for row in mean_std_rows:
        print(
            f"- {row['model']:<18} {row['metric']}: {row['mean_pm_std_pct']} "
            f"(n={row['n']})"
        )

    print("\nPaired t-test")
    for row in paired_t_rows:
        print(
            f"- {row['model_a']} vs {row['model_b']} [{row['metric']}]: "
            f"t={row['t_statistic']}, p={row['p_value']}, "
            f"mean_diff={row['mean_diff_a_minus_b']}, n={row['n']}"
        )


def main():
    args = parse_args()
    csv_path = Path(args.input_csv).resolve()
    if not csv_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    output_dir = Path(args.output_dir).resolve() if args.output_dir else csv_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    prefix = args.prefix or csv_path.stem

    fieldnames, rows = load_rows(csv_path)
    models = infer_models(fieldnames)
    if not models:
        raise ValueError("Could not infer any model columns from the input CSV.")

    mean_std_rows = analyze_mean_std(rows, models)
    paired_t_rows = analyze_paired_tests(rows, models, args.alpha)

    mean_std_path = output_dir / f"{prefix}_mean_std_table.csv"
    paired_t_path = output_dir / f"{prefix}_paired_t_test_results.csv"

    write_csv(
        mean_std_path,
        ["model_key", "model", "metric", "n", "mean", "std", "mean_pm_std", "mean_pm_std_pct"],
        mean_std_rows,
    )
    write_csv(
        paired_t_path,
        [
            "model_a_key",
            "model_a",
            "model_b_key",
            "model_b",
            "metric",
            "n",
            "paired_seeds",
            "mean_a",
            "std_a",
            "mean_b",
            "std_b",
            "mean_diff_a_minus_b",
            "std_diff",
            "t_statistic",
            "p_value",
            "significant",
        ],
        paired_t_rows,
    )
    print_terminal_summary(mean_std_rows, paired_t_rows)
    print(f"\nSaved mean ± std table: {mean_std_path}")
    print(f"Saved paired t-test CSV: {paired_t_path}")


if __name__ == "__main__":
    main()
